In [2]:
import pandas as pd
import numpy as np
import datetime as dt

In [4]:
train_df = pd.read_csv('train.csv')

In [5]:
train_df.head()

,Title,Address.1st.Line,Address.2nd.Line,City,State,Zip.Code,License.Type,License.Issue.Date,Dental.School,Graduation.Date,broker.ID,approach.date,convert
0,DMD,6335 E. Mountain View,NaN,Paradise Valley,AZ,85253,Dentist License,1987-06-10,U of Pittsburg,01/01/1970,chris,2017-08-04,1
1,DDS,24 N Bullmoose Cir,NaN,Chandler,AZ,85224,Dentist License,2009-06-11,SUNY,06/01/2007,chris,2017-06-17,0
2,DDS,2470 W Ray Road Suite 1,NaN,Chandler,AZ,85224,Dentist License,2001-07-16,U of TX/SA,05/26/2001,karl,2017-07-03,0
3,DDS,6649 East Valle Di Cadore,NaN,Tucson,AZ,85750,Dentist License,1963-01-01,NW,01/01/1957,chris,2016-11-14,0
4,DDS,6938 E. Gary,NaN,Scottsdale,AZ,85254,Dentist License,1979-12-13,U of Detroit,01/01/1965,sarah,2017-08-27,0

In [7]:
train_df['License.Type']

array(['Dentist License'], dtype=object)

Title                   52
Address.1st.Line         0
Address.2nd.Line      2877
City                     0
State                    0
Zip.Code                 0
License.Type             0
License.Issue.Date       0
Dental.School            1
Graduation.Date          0
broker.ID                0
approach.date            0
convert                  0
dtype: int64

In [11]:
train_df['License.Issue.Date'] = pd.to_datetime(train_df.loc[:, 'License.Issue.Date'], )

In [12]:
date_today = dt.datetime.now()

In [13]:
train_df['time_since_license'] = train_df['License.Issue.Date'].apply(lambda x: date_today - x)

In [15]:
def get_days(timedelta_obj):
    obj = str(timedelta_obj)
    return int(obj.split(' ')[0])#get just the days

In [17]:
train_df.time_since_license = train_df.time_since_license.apply(lambda x: get_days(x))

In [18]:
train_df.head()

,Title,Address.1st.Line,Address.2nd.Line,City,State,Zip.Code,License.Type,License.Issue.Date,Dental.School,Graduation.Date,broker.ID,approach.date,convert,time_since_license
0,DMD,6335 E. Mountain View,NaN,Paradise Valley,AZ,85253,Dentist License,1987-06-10,U of Pittsburg,01/01/1970,chris,2017-08-04,1,11553
1,DDS,24 N Bullmoose Cir,NaN,Chandler,AZ,85224,Dentist License,2009-06-11,SUNY,06/01/2007,chris,2017-06-17,0,3516
2,DDS,2470 W Ray Road Suite 1,NaN,Chandler,AZ,85224,Dentist License,2001-07-16,U of TX/SA,05/26/2001,karl,2017-07-03,0,6403
3,DDS,6649 East Valle Di Cadore,NaN,Tucson,AZ,85750,Dentist License,1963-01-01,NW,01/01/1957,chris,2016-11-14,0,20479
4,DDS,6938 E. Gary,NaN,Scottsdale,AZ,85254,Dentist License,1979-12-13,U of Detroit,01/01/1965,sarah,2017-08-27,0,14289